name: Build and Release JAR

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: 'corretto'

      #- name: Get Version from build.gradle
      #  id: extract-version
      #  run: echo "::set-output name=version::$(cat build.gradle | grep -oP 'version = '\''\K[^'\'']+')"


      - name: Build JAR
        run: ./gradlew clean build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/libs/*.jar
          release_name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
